### ISSUE TITLE
[question] Property importance

### ISSUE THREAD

**Issue by ale1313** [ThomyR73/ReactNativeRickAndMortyApiChallenge#4]
`flex-start` is the default value for this property. Is it really necessary in this case?

https://github.com/ThomyR73/ReactNativeRickAndMortyApiChallenge/blob/ea3d5111a8caaef24cd103f8a4f0509d58430366/components/Card.tsx#L70

**Comment by ThomyR73** [comment]
No, it isn't necessary, i added it on an older version and then i forgot remove it
